//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fishShooting.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListRoomInfoRequestBean")]
  public partial class ListRoomInfoRequestBean : global::ProtoBuf.IExtensible
  {
    public ListRoomInfoRequestBean() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfoResponseBean")]
  public partial class RoomInfoResponseBean : global::ProtoBuf.IExtensible
  {
    public RoomInfoResponseBean() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private long _min_gold = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"min_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long min_gold
    {
      get { return _min_gold; }
      set { _min_gold = value; }
    }
    private long _base_gun = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"base_gun", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long base_gun
    {
      get { return _base_gun; }
      set { _base_gun = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListRoomInfoResponseBean")]
  public partial class ListRoomInfoResponseBean : global::ProtoBuf.IExtensible
  {
    public ListRoomInfoResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.RoomInfoResponseBean> _list_room = new global::System.Collections.Generic.List<com.nope.fishing.RoomInfoResponseBean>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list_room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.RoomInfoResponseBean> list_room
    {
      get { return _list_room; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FishInfoResponseBean")]
  public partial class FishInfoResponseBean : global::ProtoBuf.IExtensible
  {
    public FishInfoResponseBean() {}
    
    private int _fish_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fish_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fish_id
    {
      get { return _fish_id; }
      set { _fish_id = value; }
    }
    private int _type_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type_id
    {
      get { return _type_id; }
      set { _type_id = value; }
    }
    private int _group_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private int _index_in_group;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"index_in_group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index_in_group
    {
      get { return _index_in_group; }
      set { _index_in_group = value; }
    }
    private int _path_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"path_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int path_id
    {
      get { return _path_id; }
      set { _path_id = value; }
    }
    private int _timer;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private int _type_shadow = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"type_shadow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type_shadow
    {
      get { return _type_shadow; }
      set { _type_shadow = value; }
    }
    private int _price = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HashTimingSpawnFishResponseBean")]
  public partial class HashTimingSpawnFishResponseBean : global::ProtoBuf.IExtensible
  {
    public HashTimingSpawnFishResponseBean() {}
    
    private int _time_spawn;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time_spawn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time_spawn
    {
      get { return _time_spawn; }
      set { _time_spawn = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.FishInfoResponseBean> _hash_fish_spawn = new global::System.Collections.Generic.List<com.nope.fishing.FishInfoResponseBean>();
    [global::ProtoBuf.ProtoMember(3, Name=@"hash_fish_spawn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.FishInfoResponseBean> hash_fish_spawn
    {
      get { return _hash_fish_spawn; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimingSpawnFishResponseBean")]
  public partial class TimingSpawnFishResponseBean : global::ProtoBuf.IExtensible
  {
    public TimingSpawnFishResponseBean() {}
    
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _currentState = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"currentState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int currentState
    {
      get { return _currentState; }
      set { _currentState = value; }
    }
    private float _currentStateTime = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"currentStateTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float currentStateTime
    {
      get { return _currentStateTime; }
      set { _currentStateTime = value; }
    }
    private int _stateDuringTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stateDuringTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stateDuringTime
    {
      get { return _stateDuringTime; }
      set { _stateDuringTime = value; }
    }
    private long _timestampStartState = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timestampStartState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestampStartState
    {
      get { return _timestampStartState; }
      set { _timestampStartState = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.HashTimingSpawnFishResponseBean> _hasTimingPawnFish = new global::System.Collections.Generic.List<com.nope.fishing.HashTimingSpawnFishResponseBean>();
    [global::ProtoBuf.ProtoMember(4, Name=@"hasTimingPawnFish", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.HashTimingSpawnFishResponseBean> hasTimingPawnFish
    {
      get { return _hasTimingPawnFish; }
    }
  
    private int _bg_id = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bg_id
    {
      get { return _bg_id; }
      set { _bg_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimingSpawnFishRequestBean")]
  public partial class TimingSpawnFishRequestBean : global::ProtoBuf.IExtensible
  {
    public TimingSpawnFishRequestBean() {}
    
    private int _table_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BulletRequestBean")]
  public partial class BulletRequestBean : global::ProtoBuf.IExtensible
  {
    public BulletRequestBean() {}
    
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _angle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private int _bullet_temp_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bullet_temp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bullet_temp_id
    {
      get { return _bullet_temp_id; }
      set { _bullet_temp_id = value; }
    }
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BulletResponseBean")]
  public partial class BulletResponseBean : global::ProtoBuf.IExtensible
  {
    public BulletResponseBean() {}
    
    private int _bullet_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bullet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bullet_id
    {
      get { return _bullet_id; }
      set { _bullet_id = value; }
    }
    private int _bullet_temp_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bullet_temp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bullet_temp_id
    {
      get { return _bullet_temp_id; }
      set { _bullet_temp_id = value; }
    }
    private int _gun_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gun_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gun_id
    {
      get { return _gun_id; }
      set { _gun_id = value; }
    }
    private float _pos_x = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private bool _isSuper = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isSuper", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isSuper
    {
      get { return _isSuper; }
      set { _isSuper = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeGunRequestBean")]
  public partial class ChangeGunRequestBean : global::ProtoBuf.IExtensible
  {
    public ChangeGunRequestBean() {}
    
    private int _gun_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gun_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gun_id
    {
      get { return _gun_id; }
      set { _gun_id = value; }
    }
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeGunResponseBean")]
  public partial class ChangeGunResponseBean : global::ProtoBuf.IExtensible
  {
    public ChangeGunResponseBean() {}
    
    private int _gun_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gun_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gun_id
    {
      get { return _gun_id; }
      set { _gun_id = value; }
    }
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerChangeSuperGun")]
  public partial class OtherPlayerChangeSuperGun : global::ProtoBuf.IExtensible
  {
    public OtherPlayerChangeSuperGun() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private bool _isSuper;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isSuper", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuper
    {
      get { return _isSuper; }
      set { _isSuper = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerGetFreeBullet")]
  public partial class OtherPlayerGetFreeBullet : global::ProtoBuf.IExtensible
  {
    public OtherPlayerGetFreeBullet() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _countBulletFree;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"countBulletFree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int countBulletFree
    {
      get { return _countBulletFree; }
      set { _countBulletFree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InstantJoinTableRequestBean")]
  public partial class InstantJoinTableRequestBean : global::ProtoBuf.IExtensible
  {
    public InstantJoinTableRequestBean() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinTableRequestBean")]
  public partial class JoinTableRequestBean : global::ProtoBuf.IExtensible
  {
    public JoinTableRequestBean() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinTableResponseBean")]
  public partial class JoinTableResponseBean : global::ProtoBuf.IExtensible
  {
    public JoinTableResponseBean() {}
    
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _table_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.PlayerInfoBean> _player_info = new global::System.Collections.Generic.List<com.nope.fishing.PlayerInfoBean>();
    [global::ProtoBuf.ProtoMember(4, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.PlayerInfoBean> player_info
    {
      get { return _player_info; }
    }
  
    private int _current_time_stamp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"current_time_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_time_stamp
    {
      get { return _current_time_stamp; }
      set { _current_time_stamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeSlotRequestBean")]
  public partial class ChangeSlotRequestBean : global::ProtoBuf.IExtensible
  {
    public ChangeSlotRequestBean() {}
    
    private int _slot_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeSlotResponseBean")]
  public partial class ChangeSlotResponseBean : global::ProtoBuf.IExtensible
  {
    public ChangeSlotResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherChangeSlotResponseBean")]
  public partial class OtherChangeSlotResponseBean : global::ProtoBuf.IExtensible
  {
    public OtherChangeSlotResponseBean() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _slot_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeStateResponseBean")]
  public partial class ChangeStateResponseBean : global::ProtoBuf.IExtensible
  {
    public ChangeStateResponseBean() {}
    
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _state_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state_id
    {
      get { return _state_id; }
      set { _state_id = value; }
    }
    private int _bg_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bg_id
    {
      get { return _bg_id; }
      set { _bg_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HitFishRequestBean")]
  public partial class HitFishRequestBean : global::ProtoBuf.IExtensible
  {
    public HitFishRequestBean() {}
    
    private int _timer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private int _fish_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fish_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fish_id
    {
      get { return _fish_id; }
      set { _fish_id = value; }
    }
    private int _bullet_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bullet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bullet_id
    {
      get { return _bullet_id; }
      set { _bullet_id = value; }
    }
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MissBulletRequestBean")]
  public partial class MissBulletRequestBean : global::ProtoBuf.IExtensible
  {
    public MissBulletRequestBean() {}
    
    private int _bullet_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bullet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bullet_id
    {
      get { return _bullet_id; }
      set { _bullet_id = value; }
    }
    private int _table_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FishHasBeenKillResponseBean")]
  public partial class FishHasBeenKillResponseBean : global::ProtoBuf.IExtensible
  {
    public FishHasBeenKillResponseBean() {}
    
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _timer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private int _fish_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fish_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fish_id
    {
      get { return _fish_id; }
      set { _fish_id = value; }
    }
    private int _receive_money = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"receive_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int receive_money
    {
      get { return _receive_money; }
      set { _receive_money = value; }
    }
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.FishHasBeenHoleResponseBean> _list_fish_hole = new global::System.Collections.Generic.List<com.nope.fishing.FishHasBeenHoleResponseBean>();
    [global::ProtoBuf.ProtoMember(6, Name=@"list_fish_hole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.FishHasBeenHoleResponseBean> list_fish_hole
    {
      get { return _list_fish_hole; }
    }
  
    private bool _isDouble = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isDouble", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isDouble
    {
      get { return _isDouble; }
      set { _isDouble = value; }
    }
    private int _typeShadow = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"typeShadow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int typeShadow
    {
      get { return _typeShadow; }
      set { _typeShadow = value; }
    }
    private int _typeEffectLigting = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"typeEffectLigting", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int typeEffectLigting
    {
      get { return _typeEffectLigting; }
      set { _typeEffectLigting = value; }
    }
    private int _typeEffectPLT = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"typeEffectPLT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int typeEffectPLT
    {
      get { return _typeEffectPLT; }
      set { _typeEffectPLT = value; }
    }
    private bool _isJackpot = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"isJackpot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isJackpot
    {
      get { return _isJackpot; }
      set { _isJackpot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BossGrowUpResponseBean")]
  public partial class BossGrowUpResponseBean : global::ProtoBuf.IExtensible
  {
    public BossGrowUpResponseBean() {}
    
    private int _fish_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fish_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fish_id
    {
      get { return _fish_id; }
      set { _fish_id = value; }
    }
    private int _new_price;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"new_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int new_price
    {
      get { return _new_price; }
      set { _new_price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoneyCurrentResponseBean")]
  public partial class MoneyCurrentResponseBean : global::ProtoBuf.IExtensible
  {
    public MoneyCurrentResponseBean() {}
    
    private int _fish_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fish_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fish_id
    {
      get { return _fish_id; }
      set { _fish_id = value; }
    }
    private int _price;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FishHasBeenHoleResponseBean")]
  public partial class FishHasBeenHoleResponseBean : global::ProtoBuf.IExtensible
  {
    public FishHasBeenHoleResponseBean() {}
    
    private int _timer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private int _fish_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fish_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fish_id
    {
      get { return _fish_id; }
      set { _fish_id = value; }
    }
    private int _receive_money = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"receive_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int receive_money
    {
      get { return _receive_money; }
      set { _receive_money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherJoinResponseBean")]
  public partial class OtherJoinResponseBean : global::ProtoBuf.IExtensible
  {
    public OtherJoinResponseBean() {}
    
    private com.nope.fishing.PlayerInfoBean _player_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.nope.fishing.PlayerInfoBean player_info
    {
      get { return _player_info; }
      set { _player_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaveTableRequestBean")]
  public partial class LeaveTableRequestBean : global::ProtoBuf.IExtensible
  {
    public LeaveTableRequestBean() {}
    
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaveTableResponseBean")]
  public partial class LeaveTableResponseBean : global::ProtoBuf.IExtensible
  {
    public LeaveTableResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherLeaveTableResponseBean")]
  public partial class OtherLeaveTableResponseBean : global::ProtoBuf.IExtensible
  {
    public OtherLeaveTableResponseBean() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfoBean")]
  public partial class PlayerInfoBean : global::ProtoBuf.IExtensible
  {
    public PlayerInfoBean() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _display_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"display_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string display_name
    {
      get { return _display_name; }
      set { _display_name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private long _money;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _gun_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gun_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gun_id
    {
      get { return _gun_id; }
      set { _gun_id = value; }
    }
    private int _slot_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"slot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot_id
    {
      get { return _slot_id; }
      set { _slot_id = value; }
    }
    private bool _is_host = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_host
    {
      get { return _is_host; }
      set { _is_host = value; }
    }
    private bool _is_bot = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"is_bot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_bot
    {
      get { return _is_bot; }
      set { _is_bot = value; }
    }
    private int _count_so = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"count_so", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count_so
    {
      get { return _count_so; }
      set { _count_so = value; }
    }
    private int _countBulletFree = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"countBulletFree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int countBulletFree
    {
      get { return _countBulletFree; }
      set { _countBulletFree = value; }
    }
    private long _moneyBulletFree = default(long);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"moneyBulletFree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long moneyBulletFree
    {
      get { return _moneyBulletFree; }
      set { _moneyBulletFree = value; }
    }
    private long _timeBulletFree = default(long);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"timeBulletFree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timeBulletFree
    {
      get { return _timeBulletFree; }
      set { _timeBulletFree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JackPot")]
  public partial class JackPot : global::ProtoBuf.IExtensible
  {
    public JackPot() {}
    
    private long _jack_pot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"jack_pot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long jack_pot
    {
      get { return _jack_pot; }
      set { _jack_pot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataAgency")]
  public partial class DataAgency : global::ProtoBuf.IExtensible
  {
    public DataAgency() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.AgencyInfoFromMongo> _listAgency = new global::System.Collections.Generic.List<com.nope.fishing.AgencyInfoFromMongo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listAgency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.AgencyInfoFromMongo> listAgency
    {
      get { return _listAgency; }
    }
  
    private string _regionalName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"regionalName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string regionalName
    {
      get { return _regionalName; }
      set { _regionalName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AgencyInfoFromMongo")]
  public partial class AgencyInfoFromMongo : global::ProtoBuf.IExtensible
  {
    public AgencyInfoFromMongo() {}
    
    private string _agencyName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agencyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string agencyName
    {
      get { return _agencyName; }
      set { _agencyName = value; }
    }
    private string _phoneNumber = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"phoneNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phoneNumber
    {
      get { return _phoneNumber; }
      set { _phoneNumber = value; }
    }
    private string _address = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }
    private string _zalo = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"zalo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zalo
    {
      get { return _zalo; }
      set { _zalo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataRank")]
  public partial class DataRank : global::ProtoBuf.IExtensible
  {
    public DataRank() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.RankInfoFromMongo> _listRank = new global::System.Collections.Generic.List<com.nope.fishing.RankInfoFromMongo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listRank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.RankInfoFromMongo> listRank
    {
      get { return _listRank; }
    }
  
    private string _type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankInfoFromMongo")]
  public partial class RankInfoFromMongo : global::ProtoBuf.IExtensible
  {
    public RankInfoFromMongo() {}
    
    private string _rank = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _value = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request_DailyReward")]
  public partial class Request_DailyReward : global::ProtoBuf.IExtensible
  {
    public Request_DailyReward() {}
    
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private bool _daily_reward = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"daily_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool daily_reward
    {
      get { return _daily_reward; }
      set { _daily_reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}