//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TaiXiuGame.proto
// Note: requires additional types generated from: JackpotGame.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXJoinRequest")]
  public partial class TXJoinRequest : global::ProtoBuf.IExtensible
  {
    public TXJoinRequest() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXLeaveGameResponse")]
  public partial class TXLeaveGameResponse : global::ProtoBuf.IExtensible
  {
    public TXLeaveGameResponse() {}
    
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXRoomInfo")]
  public partial class TXRoomInfo : global::ProtoBuf.IExtensible
  {
    public TXRoomInfo() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _totalPlayerBetTai = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"totalPlayerBetTai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalPlayerBetTai
    {
      get { return _totalPlayerBetTai; }
      set { _totalPlayerBetTai = value; }
    }
    private int _totalPlayerBetXiu = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalPlayerBetXiu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalPlayerBetXiu
    {
      get { return _totalPlayerBetXiu; }
      set { _totalPlayerBetXiu = value; }
    }
    private long _totalBetAmountTai = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"totalBetAmountTai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long totalBetAmountTai
    {
      get { return _totalBetAmountTai; }
      set { _totalBetAmountTai = value; }
    }
    private long _totalBetAmountXiu = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"totalBetAmountXiu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long totalBetAmountXiu
    {
      get { return _totalBetAmountXiu; }
      set { _totalBetAmountXiu = value; }
    }
    private int _countDown = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"countDown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int countDown
    {
      get { return _countDown; }
      set { _countDown = value; }
    }
    private int _timeStartNewGame = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"timeStartNewGame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timeStartNewGame
    {
      get { return _timeStartNewGame; }
      set { _timeStartNewGame = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private double _delayTime = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"delayTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double delayTime
    {
      get { return _delayTime; }
      set { _delayTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXGameInfo")]
  public partial class TXGameInfo : global::ProtoBuf.IExtensible
  {
    public TXGameInfo() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TXRoomInfo> _room = new global::System.Collections.Generic.List<com.nope.fishing.TXRoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TXRoomInfo> room
    {
      get { return _room; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXBetInfo")]
  public partial class TXBetInfo : global::ProtoBuf.IExtensible
  {
    public TXBetInfo() {}
    
    private long _userMoney = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userMoney
    {
      get { return _userMoney; }
      set { _userMoney = value; }
    }
    private long _betAmount = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"betAmount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betAmount
    {
      get { return _betAmount; }
      set { _betAmount = value; }
    }
    private long _totalBetAmount = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalBetAmount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long totalBetAmount
    {
      get { return _totalBetAmount; }
      set { _totalBetAmount = value; }
    }
    private bool _isTai = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isTai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isTai
    {
      get { return _isTai; }
      set { _isTai = value; }
    }
    private bool _isXiu = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isXiu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isXiu
    {
      get { return _isXiu; }
      set { _isXiu = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DiceHistory")]
  public partial class DiceHistory : global::ProtoBuf.IExtensible
  {
    public DiceHistory() {}
    
    private int _dice1 = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice1
    {
      get { return _dice1; }
      set { _dice1 = value; }
    }
    private int _dice2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice2
    {
      get { return _dice2; }
      set { _dice2 = value; }
    }
    private int _dice3 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dice3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice3
    {
      get { return _dice3; }
      set { _dice3 = value; }
    }
    private int _session = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int session
    {
      get { return _session; }
      set { _session = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.ListDice> _listDice = new global::System.Collections.Generic.List<com.nope.fishing.ListDice>();
    [global::ProtoBuf.ProtoMember(5, Name=@"listDice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.ListDice> listDice
    {
      get { return _listDice; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListDice")]
  public partial class ListDice : global::ProtoBuf.IExtensible
  {
    public ListDice() {}
    
    private readonly global::System.Collections.Generic.List<int> _listDiceResults = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listDiceResults", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> listDiceResults
    {
      get { return _listDiceResults; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXServerNotification")]
  public partial class TXServerNotification : global::ProtoBuf.IExtensible
  {
    public TXServerNotification() {}
    
    private readonly global::System.Collections.Generic.List<string> _TXNotification = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"TXNotification", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> TXNotification
    {
      get { return _TXNotification; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXResult")]
  public partial class TXResult : global::ProtoBuf.IExtensible
  {
    public TXResult() {}
    
    private readonly global::System.Collections.Generic.List<int> _FinalResult = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"FinalResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> FinalResult
    {
      get { return _FinalResult; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Dice1 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Dice1
    {
      get { return _Dice1; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Dice2 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Dice2
    {
      get { return _Dice2; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Dice3 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Dice3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Dice3
    {
      get { return _Dice3; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _TaiXiu_TrueFalse = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(5, Name=@"TaiXiu_TrueFalse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> TaiXiu_TrueFalse
    {
      get { return _TaiXiu_TrueFalse; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _FinalResultForGrapth3 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"FinalResultForGrapth3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> FinalResultForGrapth3
    {
      get { return _FinalResultForGrapth3; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _FinalResultForGrapth4 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"FinalResultForGrapth4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> FinalResultForGrapth4
    {
      get { return _FinalResultForGrapth4; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXResult_one")]
  public partial class TXResult_one : global::ProtoBuf.IExtensible
  {
    public TXResult_one() {}
    
    private int _FinalResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"FinalResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FinalResult
    {
      get { return _FinalResult; }
      set { _FinalResult = value; }
    }
    private int _Dice1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Dice1
    {
      get { return _Dice1; }
      set { _Dice1 = value; }
    }
    private int _Dice2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Dice2
    {
      get { return _Dice2; }
      set { _Dice2 = value; }
    }
    private int _Dice3 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Dice3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Dice3
    {
      get { return _Dice3; }
      set { _Dice3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}