//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: userMessage.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequestBean")]
  public partial class LoginRequestBean : global::ProtoBuf.IExtensible
  {
    public LoginRequestBean() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponseBean")]
  public partial class LoginResponseBean : global::ProtoBuf.IExtensible
  {
    public LoginResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private string _avatar_url = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"avatar_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avatar_url
    {
      get { return _avatar_url; }
      set { _avatar_url = value; }
    }
    private long _gold = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private long _silver = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"silver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long silver
    {
      get { return _silver; }
      set { _silver = value; }
    }
    private long _time_stamp_at_login = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"time_stamp_at_login", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time_stamp_at_login
    {
      get { return _time_stamp_at_login; }
      set { _time_stamp_at_login = value; }
    }
    private int _daily_reward_day = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"daily_reward_day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int daily_reward_day
    {
      get { return _daily_reward_day; }
      set { _daily_reward_day = value; }
    }
    private bool _recievedDailyReward = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"recievedDailyReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool recievedDailyReward
    {
      get { return _recievedDailyReward; }
      set { _recievedDailyReward = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _mail = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mail
    {
      get { return _mail; }
      set { _mail = value; }
    }
    private string _phone = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private bool _is_verify_phone = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"is_verify_phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_verify_phone
    {
      get { return _is_verify_phone; }
      set { _is_verify_phone = value; }
    }
    private bool _is_banned = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"is_banned", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_banned
    {
      get { return _is_banned; }
      set { _is_banned = value; }
    }
    private long _goldFrWallet = default(long);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"goldFrWallet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long goldFrWallet
    {
      get { return _goldFrWallet; }
      set { _goldFrWallet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListDailyRewardResponseBean")]
  public partial class ListDailyRewardResponseBean : global::ProtoBuf.IExtensible
  {
    public ListDailyRewardResponseBean() {}
    
    private int _daily_reward_day;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"daily_reward_day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int daily_reward_day
    {
      get { return _daily_reward_day; }
      set { _daily_reward_day = value; }
    }
    private bool _revicedRewardToday = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"revicedRewardToday", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool revicedRewardToday
    {
      get { return _revicedRewardToday; }
      set { _revicedRewardToday = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.InfoDailyRewardResponseBean> _listDailyReward = new global::System.Collections.Generic.List<com.nope.fishing.InfoDailyRewardResponseBean>();
    [global::ProtoBuf.ProtoMember(3, Name=@"listDailyReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.InfoDailyRewardResponseBean> listDailyReward
    {
      get { return _listDailyReward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InfoDailyRewardResponseBean")]
  public partial class InfoDailyRewardResponseBean : global::ProtoBuf.IExtensible
  {
    public InfoDailyRewardResponseBean() {}
    
    private int _day;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int day
    {
      get { return _day; }
      set { _day = value; }
    }
    private long _gold_reward = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold_reward
    {
      get { return _gold_reward; }
      set { _gold_reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailyRewardRequestBean")]
  public partial class DailyRewardRequestBean : global::ProtoBuf.IExtensible
  {
    public DailyRewardRequestBean() {}
    
    private int _day;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int day
    {
      get { return _day; }
      set { _day = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailyRewardResponseBean")]
  public partial class DailyRewardResponseBean : global::ProtoBuf.IExtensible
  {
    public DailyRewardResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _day = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int day
    {
      get { return _day; }
      set { _day = value; }
    }
    private long _gold_reward = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gold_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold_reward
    {
      get { return _gold_reward; }
      set { _gold_reward = value; }
    }
    private long _silver_reward = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"silver_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long silver_reward
    {
      get { return _silver_reward; }
      set { _silver_reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutRequestBean")]
  public partial class LogoutRequestBean : global::ProtoBuf.IExtensible
  {
    public LogoutRequestBean() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DisconnectResponseBean")]
  public partial class DisconnectResponseBean : global::ProtoBuf.IExtensible
  {
    public DisconnectResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _error_description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_description
    {
      get { return _error_description; }
      set { _error_description = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AvatarRequestBean")]
  public partial class AvatarRequestBean : global::ProtoBuf.IExtensible
  {
    public AvatarRequestBean() {}
    
    private int _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AvatarResponseBean")]
  public partial class AvatarResponseBean : global::ProtoBuf.IExtensible
  {
    public AvatarResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateUserInfoRequestBean")]
  public partial class UpdateUserInfoRequestBean : global::ProtoBuf.IExtensible
  {
    public UpdateUserInfoRequestBean() {}
    
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _mail = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mail
    {
      get { return _mail; }
      set { _mail = value; }
    }
    private string _phone = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private string _avatar = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateUserInfoResponseBean")]
  public partial class UpdateUserInfoResponseBean : global::ProtoBuf.IExtensible
  {
    public UpdateUserInfoResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _error_description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_description
    {
      get { return _error_description; }
      set { _error_description = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateGoldAndSilverRequestBean")]
  public partial class UpdateGoldAndSilverRequestBean : global::ProtoBuf.IExtensible
  {
    public UpdateGoldAndSilverRequestBean() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateGoldAndSilverResponseBean")]
  public partial class UpdateGoldAndSilverResponseBean : global::ProtoBuf.IExtensible
  {
    public UpdateGoldAndSilverResponseBean() {}
    
    private long _gold;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private long _silver;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"silver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long silver
    {
      get { return _silver; }
      set { _silver = value; }
    }
    private int _ticketWheel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ticketWheel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ticketWheel
    {
      get { return _ticketWheel; }
      set { _ticketWheel = value; }
    }
    private int _countMailNotRead = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"countMailNotRead", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int countMailNotRead
    {
      get { return _countMailNotRead; }
      set { _countMailNotRead = value; }
    }
    private int _countNewsNotRead = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"countNewsNotRead", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int countNewsNotRead
    {
      get { return _countNewsNotRead; }
      set { _countNewsNotRead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInfoOtherUserRequestBean")]
  public partial class GetInfoOtherUserRequestBean : global::ProtoBuf.IExtensible
  {
    public GetInfoOtherUserRequestBean() {}
    
    private int _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInfoOtherUserResponseBean")]
  public partial class GetInfoOtherUserResponseBean : global::ProtoBuf.IExtensible
  {
    public GetInfoOtherUserResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private string _avatar_url = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"avatar_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avatar_url
    {
      get { return _avatar_url; }
      set { _avatar_url = value; }
    }
    private long _gold = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private long _silver = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"silver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long silver
    {
      get { return _silver; }
      set { _silver = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _mail = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mail
    {
      get { return _mail; }
      set { _mail = value; }
    }
    private string _phone = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private bool _is_friend = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"is_friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_friend
    {
      get { return _is_friend; }
      set { _is_friend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOTPRequestBean")]
  public partial class GetOTPRequestBean : global::ProtoBuf.IExtensible
  {
    public GetOTPRequestBean() {}
    
    private int _action;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private string _phone = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOTPResponseBean")]
  public partial class GetOTPResponseBean : global::ProtoBuf.IExtensible
  {
    public GetOTPResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyPhoneRequestBean")]
  public partial class VerifyPhoneRequestBean : global::ProtoBuf.IExtensible
  {
    public VerifyPhoneRequestBean() {}
    
    private string _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _phone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyPhoneResponseBean")]
  public partial class VerifyPhoneResponseBean : global::ProtoBuf.IExtensible
  {
    public VerifyPhoneResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}