package games.core.game;

public interface GameErrorCode {
    int GAME_NOT_ACTIVE = 1998;
    int NOT_FOUND_GAME = 1999;
    int PLAYER_NOT_FOUND_IN_GAME = 2000;
    int CANNOT_CREATE_PLAYER = 2001;
    int DUPLICATE_PLAYER_IN_GAME = 2002;
    int PLAYER_NOT_ENOUGH_MONEY = 2003;
    int PLAYER_NOT_FOUND_IN_DATABASE = 2004;
    int ROOM_NOT_EXIST_IN_GAME = 2005;
    int DUPLICATE_PLAYER_IN_ROOM = 2006;
    int NOT_FOUND_PLAYER_IN_ROOM = 2007;
    int CANNOT_REMOVE_PLAYER_IN_GAME = 2008;
    int CANNOT_REMOVE_PLAYER_IN_ROOM = 2009;
    int TABLE_IS_FULL = 2010;
    int PLAYER_CAN_NOT_JOIN_ROOM = 2011;
    int PLAYER_CAN_NOT_JOIN_TABLE = 2012;
    int PLAYER_IS_NOT_PLAYING = 2013;
    int PLAYER_IS_PLAYING_NOW = 2014;
    int NOT_FOUND_PLAYER_IN_TABLE = 2015;
    int CANNOT_SUB_USER_MONEY = 2016;
    int MONEY_AMOUNT_NOT_VALID = 2017;
    int NOT_FOUND_TABLE_IN_ROOM = 2018;
    int CAN_NOT_LESS_THAN_ZERO = 2019;
    int ERROR_NOT_DEFINE = 999;
}
