//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/feature.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankUserInfo")]
  public partial class RankUserInfo : global::ProtoBuf.IExtensible
  {
    public RankUserInfo() {}
    
    private int _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private long _gold = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private long _total_win_gold = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"total_win_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long total_win_gold
    {
      get { return _total_win_gold; }
      set { _total_win_gold = value; }
    }
    private string _avatar = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private int _rank;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private bool _is_top_rich = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"is_top_rich", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_top_rich
    {
      get { return _is_top_rich; }
      set { _is_top_rich = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankingResponse")]
  public partial class RankingResponse : global::ProtoBuf.IExtensible
  {
    public RankingResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.RankUserInfo> _list_user = new global::System.Collections.Generic.List<com.nope.fishing.RankUserInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.RankUserInfo> list_user
    {
      get { return _list_user; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListNewsResponseBean")]
  public partial class ListNewsResponseBean : global::ProtoBuf.IExtensible
  {
    public ListNewsResponseBean() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.NewsInfoBean> _list_news = new global::System.Collections.Generic.List<com.nope.fishing.NewsInfoBean>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list_news", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.NewsInfoBean> list_news
    {
      get { return _list_news; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewsInfoBean")]
  public partial class NewsInfoBean : global::ProtoBuf.IExtensible
  {
    public NewsInfoBean() {}
    
    private long _news_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"news_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long news_id
    {
      get { return _news_id; }
      set { _news_id = value; }
    }
    private string _category;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string category
    {
      get { return _category; }
      set { _category = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _url_image = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"url_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string url_image
    {
      get { return _url_image; }
      set { _url_image = value; }
    }
    private string _link = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"link", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string link
    {
      get { return _link; }
      set { _link = value; }
    }
    private bool _is_read = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"is_read", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_read
    {
      get { return _is_read; }
      set { _is_read = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadNewsRequestBean")]
  public partial class ReadNewsRequestBean : global::ProtoBuf.IExtensible
  {
    public ReadNewsRequestBean() {}
    
    private long _news_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"news_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long news_id
    {
      get { return _news_id; }
      set { _news_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadNewsResponseBean")]
  public partial class ReadNewsResponseBean : global::ProtoBuf.IExtensible
  {
    public ReadNewsResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private long _news_id = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"news_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long news_id
    {
      get { return _news_id; }
      set { _news_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListInboxMessageResponseBean")]
  public partial class ListInboxMessageResponseBean : global::ProtoBuf.IExtensible
  {
    public ListInboxMessageResponseBean() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.InboxMessageBean> _list_inbox_message = new global::System.Collections.Generic.List<com.nope.fishing.InboxMessageBean>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list_inbox_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.InboxMessageBean> list_inbox_message
    {
      get { return _list_inbox_message; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InboxMessageBean")]
  public partial class InboxMessageBean : global::ProtoBuf.IExtensible
  {
    public InboxMessageBean() {}
    
    private long _inbox_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inbox_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long inbox_id
    {
      get { return _inbox_id; }
      set { _inbox_id = value; }
    }
    private string _from;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string from
    {
      get { return _from; }
      set { _from = value; }
    }
    private string _to;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string to
    {
      get { return _to; }
      set { _to = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _action_code = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"action_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action_code
    {
      get { return _action_code; }
      set { _action_code = value; }
    }
    private int _timestamp = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private bool _is_read;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"is_read", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_read
    {
      get { return _is_read; }
      set { _is_read = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendInboxMessageResponseBean")]
  public partial class SendInboxMessageResponseBean : global::ProtoBuf.IExtensible
  {
    public SendInboxMessageResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private com.nope.fishing.InboxMessageBean _inbox_message = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inbox_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.InboxMessageBean inbox_message
    {
      get { return _inbox_message; }
      set { _inbox_message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenInboxMessageResponseBean")]
  public partial class OpenInboxMessageResponseBean : global::ProtoBuf.IExtensible
  {
    public OpenInboxMessageResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private long _inbox_id = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inbox_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long inbox_id
    {
      get { return _inbox_id; }
      set { _inbox_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenInboxMessageRequestBean")]
  public partial class OpenInboxMessageRequestBean : global::ProtoBuf.IExtensible
  {
    public OpenInboxMessageRequestBean() {}
    
    private long _inbox_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inbox_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long inbox_id
    {
      get { return _inbox_id; }
      set { _inbox_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendInboxMessageRequestBean")]
  public partial class SendInboxMessageRequestBean : global::ProtoBuf.IExtensible
  {
    public SendInboxMessageRequestBean() {}
    
    private int _toId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"toId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toId
    {
      get { return _toId; }
      set { _toId = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveInboxMessageResponseBean")]
  public partial class RemoveInboxMessageResponseBean : global::ProtoBuf.IExtensible
  {
    public RemoveInboxMessageResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private long _inbox_id = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inbox_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long inbox_id
    {
      get { return _inbox_id; }
      set { _inbox_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveInboxMessageRequestBean")]
  public partial class RemoveInboxMessageRequestBean : global::ProtoBuf.IExtensible
  {
    public RemoveInboxMessageRequestBean() {}
    
    private long _inbox_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inbox_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long inbox_id
    {
      get { return _inbox_id; }
      set { _inbox_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushTextRunBean")]
  public partial class PushTextRunBean : global::ProtoBuf.IExtensible
  {
    public PushTextRunBean() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.PushTextRunItemBean> _pushMessage = new global::System.Collections.Generic.List<com.nope.fishing.PushTextRunItemBean>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pushMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.PushTextRunItemBean> pushMessage
    {
      get { return _pushMessage; }
    }
  
    private bool _forceShow = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"forceShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool forceShow
    {
      get { return _forceShow; }
      set { _forceShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushTextRunItemBean")]
  public partial class PushTextRunItemBean : global::ProtoBuf.IExtensible
  {
    public PushTextRunItemBean() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _link = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"link", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string link
    {
      get { return _link; }
      set { _link = value; }
    }
    private int _startTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _endTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private int _loop;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"loop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loop
    {
      get { return _loop; }
      set { _loop = value; }
    }
    private int _priority;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushDialogBean")]
  public partial class PushDialogBean : global::ProtoBuf.IExtensible
  {
    public PushDialogBean() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.PushDialogItemBean> _pushMessage = new global::System.Collections.Generic.List<com.nope.fishing.PushDialogItemBean>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pushMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.PushDialogItemBean> pushMessage
    {
      get { return _pushMessage; }
    }
  
    private bool _forceShow;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"forceShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool forceShow
    {
      get { return _forceShow; }
      set { _forceShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushDialogItemBean")]
  public partial class PushDialogItemBean : global::ProtoBuf.IExtensible
  {
    public PushDialogItemBean() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _imageUrl;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"imageUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imageUrl
    {
      get { return _imageUrl; }
      set { _imageUrl = value; }
    }
    private string _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _showTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"showTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long showTime
    {
      get { return _showTime; }
      set { _showTime = value; }
    }
    private int _priority;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendInfoBean")]
  public partial class FriendInfoBean : global::ProtoBuf.IExtensible
  {
    public FriendInfoBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _avatar_url = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"avatar_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avatar_url
    {
      get { return _avatar_url; }
      set { _avatar_url = value; }
    }
    private long _gold = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private bool _is_facebook_friend = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_facebook_friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_facebook_friend
    {
      get { return _is_facebook_friend; }
      set { _is_facebook_friend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListFriendBean")]
  public partial class ListFriendBean : global::ProtoBuf.IExtensible
  {
    public ListFriendBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.FriendInfoBean> _list_friends = new global::System.Collections.Generic.List<com.nope.fishing.FriendInfoBean>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.FriendInfoBean> list_friends
    {
      get { return _list_friends; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FindFriendRequestBean")]
  public partial class FindFriendRequestBean : global::ProtoBuf.IExtensible
  {
    public FindFriendRequestBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddFriendRequestBean")]
  public partial class AddFriendRequestBean : global::ProtoBuf.IExtensible
  {
    public AddFriendRequestBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddFriendResponseBean")]
  public partial class AddFriendResponseBean : global::ProtoBuf.IExtensible
  {
    public AddFriendResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _friend_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherRequestAddFriendBean")]
  public partial class OtherRequestAddFriendBean : global::ProtoBuf.IExtensible
  {
    public OtherRequestAddFriendBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptFriendRequestBean")]
  public partial class AcceptFriendRequestBean : global::ProtoBuf.IExtensible
  {
    public AcceptFriendRequestBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptFriendResponseBean")]
  public partial class AcceptFriendResponseBean : global::ProtoBuf.IExtensible
  {
    public AcceptFriendResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _friend_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherAcceptFriendBean")]
  public partial class OtherAcceptFriendBean : global::ProtoBuf.IExtensible
  {
    public OtherAcceptFriendBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private string _nick_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeclineFriendRequestBean")]
  public partial class DeclineFriendRequestBean : global::ProtoBuf.IExtensible
  {
    public DeclineFriendRequestBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeclineFriendResponseBean")]
  public partial class DeclineFriendResponseBean : global::ProtoBuf.IExtensible
  {
    public DeclineFriendResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _friend_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveFriendRequestBean")]
  public partial class RemoveFriendRequestBean : global::ProtoBuf.IExtensible
  {
    public RemoveFriendRequestBean() {}
    
    private int _friend_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveFriendResponseBean")]
  public partial class RemoveFriendResponseBean : global::ProtoBuf.IExtensible
  {
    public RemoveFriendResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _friend_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friend_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friend_id
    {
      get { return _friend_id; }
      set { _friend_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseGetListMission")]
  public partial class ResponseGetListMission : global::ProtoBuf.IExtensible
  {
    public ResponseGetListMission() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.MissionInfo> _list_mission_infos = new global::System.Collections.Generic.List<com.nope.fishing.MissionInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list_mission_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.MissionInfo> list_mission_infos
    {
      get { return _list_mission_infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MissionInfo")]
  public partial class MissionInfo : global::ProtoBuf.IExtensible
  {
    public MissionInfo() {}
    
    private string _mission_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mission_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mission_id
    {
      get { return _mission_id; }
      set { _mission_id = value; }
    }
    private string _user_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _mission_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mission_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mission_name
    {
      get { return _mission_name; }
      set { _mission_name = value; }
    }
    private long _day = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long day
    {
      get { return _day; }
      set { _day = value; }
    }
    private int _mission_type_id = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mission_type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mission_type_id
    {
      get { return _mission_type_id; }
      set { _mission_type_id = value; }
    }
    private long _goal = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long goal
    {
      get { return _goal; }
      set { _goal = value; }
    }
    private long _progress = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private bool _is_done = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"is_done", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_done
    {
      get { return _is_done; }
      set { _is_done = value; }
    }
    private bool _is_recieve_reward = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"is_recieve_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_recieve_reward
    {
      get { return _is_recieve_reward; }
      set { _is_recieve_reward = value; }
    }
    private long _money_reward = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"money_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money_reward
    {
      get { return _money_reward; }
      set { _money_reward = value; }
    }
    private int _ticket_wheel_reward = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ticket_wheel_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ticket_wheel_reward
    {
      get { return _ticket_wheel_reward; }
      set { _ticket_wheel_reward = value; }
    }
    private string _mission_desc = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"mission_desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mission_desc
    {
      get { return _mission_desc; }
      set { _mission_desc = value; }
    }
    private long _condition = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long condition
    {
      get { return _condition; }
      set { _condition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestMissionRecieveReward")]
  public partial class RequestMissionRecieveReward : global::ProtoBuf.IExtensible
  {
    public RequestMissionRecieveReward() {}
    
    private string _mision_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mision_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mision_id
    {
      get { return _mision_id; }
      set { _mision_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseMissionRecieveReward")]
  public partial class ResponseMissionRecieveReward : global::ProtoBuf.IExtensible
  {
    public ResponseMissionRecieveReward() {}
    
    private string _mission_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mission_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mission_id
    {
      get { return _mission_id; }
      set { _mission_id = value; }
    }
    private long _money_reward = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money_reward
    {
      get { return _money_reward; }
      set { _money_reward = value; }
    }
    private int _ticket_wheel_reward = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ticket_wheel_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ticket_wheel_reward
    {
      get { return _ticket_wheel_reward; }
      set { _ticket_wheel_reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}