//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/miniTXMessage.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseInfo")]
  public partial class MTXResponseInfo : global::ProtoBuf.IExtensible
  {
    public MTXResponseInfo() {}
    
    private long _session_id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private com.nope.fishing.State _state = com.nope.fishing.State.NONE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.State.NONE)]
    public com.nope.fishing.State state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _time_remains = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time_remains", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time_remains
    {
      get { return _time_remains; }
      set { _time_remains = value; }
    }
    private long _myBetTaiAmount = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"myBetTaiAmount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long myBetTaiAmount
    {
      get { return _myBetTaiAmount; }
      set { _myBetTaiAmount = value; }
    }
    private long _myBetXiu_amount = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"myBetXiu_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long myBetXiu_amount
    {
      get { return _myBetXiu_amount; }
      set { _myBetXiu_amount = value; }
    }
    private int _total_playerTai = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"total_playerTai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_playerTai
    {
      get { return _total_playerTai; }
      set { _total_playerTai = value; }
    }
    private long _total_betMoneyTai = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"total_betMoneyTai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long total_betMoneyTai
    {
      get { return _total_betMoneyTai; }
      set { _total_betMoneyTai = value; }
    }
    private int _total_playerXiu = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"total_playerXiu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_playerXiu
    {
      get { return _total_playerXiu; }
      set { _total_playerXiu = value; }
    }
    private long _total_betMoneyXiu = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"total_betMoneyXiu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long total_betMoneyXiu
    {
      get { return _total_betMoneyXiu; }
      set { _total_betMoneyXiu = value; }
    }
    private com.nope.fishing.MTXListHistoryDataSimple _history_list = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"history_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.MTXListHistoryDataSimple history_list
    {
      get { return _history_list; }
      set { _history_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXListHistoryDataSimple")]
  public partial class MTXListHistoryDataSimple : global::ProtoBuf.IExtensible
  {
    public MTXListHistoryDataSimple() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryDataSimple> _listHistorySimple = new global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryDataSimple>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listHistorySimple", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryDataSimple> listHistorySimple
    {
      get { return _listHistorySimple; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXHistoryDataSimple")]
  public partial class MTXHistoryDataSimple : global::ProtoBuf.IExtensible
  {
    public MTXHistoryDataSimple() {}
    
    private long _sessionID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private com.nope.fishing.MTXBetType _result = com.nope.fishing.MTXBetType.NO_BET;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.MTXBetType.NO_BET)]
    public com.nope.fishing.MTXBetType result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _dice1 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice1
    {
      get { return _dice1; }
      set { _dice1 = value; }
    }
    private int _dice2 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice2
    {
      get { return _dice2; }
      set { _dice2 = value; }
    }
    private int _dice3 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dice3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice3
    {
      get { return _dice3; }
      set { _dice3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXHistoryData")]
  public partial class MTXHistoryData : global::ProtoBuf.IExtensible
  {
    public MTXHistoryData() {}
    
    private int _sessionID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private com.nope.fishing.MTXBetType _result = com.nope.fishing.MTXBetType.NO_BET;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.MTXBetType.NO_BET)]
    public com.nope.fishing.MTXBetType result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _dice1 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice1
    {
      get { return _dice1; }
      set { _dice1 = value; }
    }
    private int _dice2 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice2
    {
      get { return _dice2; }
      set { _dice2 = value; }
    }
    private int _dice3 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dice3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice3
    {
      get { return _dice3; }
      set { _dice3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXRequestBet")]
  public partial class MTXRequestBet : global::ProtoBuf.IExtensible
  {
    public MTXRequestBet() {}
    
    private long _money_bet = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money_bet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money_bet
    {
      get { return _money_bet; }
      set { _money_bet = value; }
    }
    private com.nope.fishing.MTXBetType _bet_type = com.nope.fishing.MTXBetType.NO_BET;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bet_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.MTXBetType.NO_BET)]
    public com.nope.fishing.MTXBetType bet_type
    {
      get { return _bet_type; }
      set { _bet_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseBet")]
  public partial class MTXResponseBet : global::ProtoBuf.IExtensible
  {
    public MTXResponseBet() {}
    
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private long _money_bet = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money_bet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money_bet
    {
      get { return _money_bet; }
      set { _money_bet = value; }
    }
    private com.nope.fishing.MTXBetType _bet_type = com.nope.fishing.MTXBetType.NO_BET;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bet_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.MTXBetType.NO_BET)]
    public com.nope.fishing.MTXBetType bet_type
    {
      get { return _bet_type; }
      set { _bet_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseDiceResult")]
  public partial class MTXResponseDiceResult : global::ProtoBuf.IExtensible
  {
    public MTXResponseDiceResult() {}
    
    private com.nope.fishing.MTXBetType _result = com.nope.fishing.MTXBetType.NO_BET;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.MTXBetType.NO_BET)]
    public com.nope.fishing.MTXBetType result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _dice1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice1
    {
      get { return _dice1; }
      set { _dice1 = value; }
    }
    private int _dice2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice2
    {
      get { return _dice2; }
      set { _dice2 = value; }
    }
    private int _dice3 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dice3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice3
    {
      get { return _dice3; }
      set { _dice3 = value; }
    }
    private long _session_id = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private com.nope.fishing.State _state = com.nope.fishing.State.NONE;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.State.NONE)]
    public com.nope.fishing.State state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _time_remains = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time_remains", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time_remains
    {
      get { return _time_remains; }
      set { _time_remains = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseChangeState")]
  public partial class MTXResponseChangeState : global::ProtoBuf.IExtensible
  {
    public MTXResponseChangeState() {}
    
    private long _session_id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private com.nope.fishing.State _state = com.nope.fishing.State.NONE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.State.NONE)]
    public com.nope.fishing.State state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _time_remains = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time_remains", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time_remains
    {
      get { return _time_remains; }
      set { _time_remains = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseHistoryDetail")]
  public partial class MTXResponseHistoryDetail : global::ProtoBuf.IExtensible
  {
    public MTXResponseHistoryDetail() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryDetailData> _list = new global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryDetailData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryDetailData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXHistoryDetailData")]
  public partial class MTXHistoryDetailData : global::ProtoBuf.IExtensible
  {
    public MTXHistoryDetailData() {}
    
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _return_amount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"return_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int return_amount
    {
      get { return _return_amount; }
      set { _return_amount = value; }
    }
    private int _bet_amount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bet_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bet_amount
    {
      get { return _bet_amount; }
      set { _bet_amount = value; }
    }
    private com.nope.fishing.MTXBetType _betType = com.nope.fishing.MTXBetType.NO_BET;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"betType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.MTXBetType.NO_BET)]
    public com.nope.fishing.MTXBetType betType
    {
      get { return _betType; }
      set { _betType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseGetTop")]
  public partial class MTXResponseGetTop : global::ProtoBuf.IExtensible
  {
    public MTXResponseGetTop() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TopDataDetail> _list_old = new global::System.Collections.Generic.List<com.nope.fishing.TopDataDetail>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list_old", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TopDataDetail> list_old
    {
      get { return _list_old; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TopDataDetail")]
  public partial class TopDataDetail : global::ProtoBuf.IExtensible
  {
    public TopDataDetail() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _total_win_money = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"total_win_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_win_money
    {
      get { return _total_win_money; }
      set { _total_win_money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXRequestHistoryDetail")]
  public partial class MTXRequestHistoryDetail : global::ProtoBuf.IExtensible
  {
    public MTXRequestHistoryDetail() {}
    
    private long _session_id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseMyHistory")]
  public partial class MTXResponseMyHistory : global::ProtoBuf.IExtensible
  {
    public MTXResponseMyHistory() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.MTXResponseUserHistoryData> _list_user_bet = new global::System.Collections.Generic.List<com.nope.fishing.MTXResponseUserHistoryData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list_user_bet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.MTXResponseUserHistoryData> list_user_bet
    {
      get { return _list_user_bet; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseUserHistoryData")]
  public partial class MTXResponseUserHistoryData : global::ProtoBuf.IExtensible
  {
    public MTXResponseUserHistoryData() {}
    
    private long _session_id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private com.nope.fishing.MTXBetType _bet_type = com.nope.fishing.MTXBetType.NO_BET;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bet_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.nope.fishing.MTXBetType.NO_BET)]
    public com.nope.fishing.MTXBetType bet_type
    {
      get { return _bet_type; }
      set { _bet_type = value; }
    }
    private string _result = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _bet_amount = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bet_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bet_amount
    {
      get { return _bet_amount; }
      set { _bet_amount = value; }
    }
    private long _return_amount = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"return_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long return_amount
    {
      get { return _return_amount; }
      set { _return_amount = value; }
    }
    private long _recieve_amount = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"recieve_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long recieve_amount
    {
      get { return _recieve_amount; }
      set { _recieve_amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseHistoryData")]
  public partial class MTXResponseHistoryData : global::ProtoBuf.IExtensible
  {
    public MTXResponseHistoryData() {}
    
    private long _session_id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private com.nope.fishing.MTXResponseDiceResult _result = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.MTXResponseDiceResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.MTXResponseBetHistoryData> _bet_tais = new global::System.Collections.Generic.List<com.nope.fishing.MTXResponseBetHistoryData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"bet_tais", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.MTXResponseBetHistoryData> bet_tais
    {
      get { return _bet_tais; }
    }
  
    private readonly global::System.Collections.Generic.List<com.nope.fishing.MTXResponseBetHistoryData> _bet_xius = new global::System.Collections.Generic.List<com.nope.fishing.MTXResponseBetHistoryData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"bet_xius", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.MTXResponseBetHistoryData> bet_xius
    {
      get { return _bet_xius; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXResponseBetHistoryData")]
  public partial class MTXResponseBetHistoryData : global::ProtoBuf.IExtensible
  {
    public MTXResponseBetHistoryData() {}
    
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private long _bet_amount = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bet_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bet_amount
    {
      get { return _bet_amount; }
      set { _bet_amount = value; }
    }
    private long _return_amount = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"return_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long return_amount
    {
      get { return _return_amount; }
      set { _return_amount = value; }
    }
    private long _recieve_amount = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"recieve_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long recieve_amount
    {
      get { return _recieve_amount; }
      set { _recieve_amount = value; }
    }
    private string _date = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string date
    {
      get { return _date; }
      set { _date = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXHistoryFullInfo")]
  public partial class MTXHistoryFullInfo : global::ProtoBuf.IExtensible
  {
    public MTXHistoryFullInfo() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryInfo> _list_history = new global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list_history", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.MTXHistoryInfo> list_history
    {
      get { return _list_history; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTXHistoryInfo")]
  public partial class MTXHistoryInfo : global::ProtoBuf.IExtensible
  {
    public MTXHistoryInfo() {}
    
    private long _session_id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private int _total_dice = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"total_dice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_dice
    {
      get { return _total_dice; }
      set { _total_dice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MTXBetType")]
    public enum MTXBetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_BET", Value=0)]
      NO_BET = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TAI", Value=1)]
      TAI = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XIU", Value=2)]
      XIU = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"State")]
    public enum State
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BETTING", Value=1)]
      BETTING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WAITING_SHOW_RESULT", Value=2)]
      WAITING_SHOW_RESULT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_RESULT", Value=3)]
      SHOW_RESULT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WAITING_NEW_MATCH", Value=4)]
      WAITING_NEW_MATCH = 4
    }
  
}