//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/shop.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessPaymentAppleRequestBean")]
  public partial class ProcessPaymentAppleRequestBean : global::ProtoBuf.IExtensible
  {
    public ProcessPaymentAppleRequestBean() {}
    
    private string _product;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"product", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string product
    {
      get { return _product; }
      set { _product = value; }
    }
    private string _transaction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"transaction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string transaction
    {
      get { return _transaction; }
      set { _transaction = value; }
    }
    private string _price;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string price
    {
      get { return _price; }
      set { _price = value; }
    }
    private byte[] _contentData;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"contentData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] contentData
    {
      get { return _contentData; }
      set { _contentData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessPaymentGoogleRequestBean")]
  public partial class ProcessPaymentGoogleRequestBean : global::ProtoBuf.IExtensible
  {
    public ProcessPaymentGoogleRequestBean() {}
    
    private string _itemtype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemtype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string itemtype
    {
      get { return _itemtype; }
      set { _itemtype = value; }
    }
    private string _signature;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private string _jsondata;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"jsondata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string jsondata
    {
      get { return _jsondata; }
      set { _jsondata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessVideoAdsRequestBean")]
  public partial class ProcessVideoAdsRequestBean : global::ProtoBuf.IExtensible
  {
    public ProcessVideoAdsRequestBean() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessPaymentIAPResponseBean")]
  public partial class ProcessPaymentIAPResponseBean : global::ProtoBuf.IExtensible
  {
    public ProcessPaymentIAPResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessPaymentErrorBean")]
  public partial class ProcessPaymentErrorBean : global::ProtoBuf.IExtensible
  {
    public ProcessPaymentErrorBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private int _payment_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"payment_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int payment_type
    {
      get { return _payment_type; }
      set { _payment_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessPaymentCardRequestBean")]
  public partial class ProcessPaymentCardRequestBean : global::ProtoBuf.IExtensible
  {
    public ProcessPaymentCardRequestBean() {}
    
    private string _card_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"card_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string card_code
    {
      get { return _card_code; }
      set { _card_code = value; }
    }
    private string _card_serial;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_serial", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string card_serial
    {
      get { return _card_serial; }
      set { _card_serial = value; }
    }
    private int _card_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }
    private int _package;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int package
    {
      get { return _package; }
      set { _package = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessCashoutCardRequestBean")]
  public partial class ProcessCashoutCardRequestBean : global::ProtoBuf.IExtensible
  {
    public ProcessCashoutCardRequestBean() {}
    
    private int _package;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int package
    {
      get { return _package; }
      set { _package = value; }
    }
    private int _card_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }
    private string _otp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"otp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string otp
    {
      get { return _otp; }
      set { _otp = value; }
    }
    private string _note = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"note", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string note
    {
      get { return _note; }
      set { _note = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessCashoutResponseBean")]
  public partial class ProcessCashoutResponseBean : global::ProtoBuf.IExtensible
  {
    public ProcessCashoutResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _card_serial = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"card_serial", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string card_serial
    {
      get { return _card_serial; }
      set { _card_serial = value; }
    }
    private string _card_code = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"card_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string card_code
    {
      get { return _card_code; }
      set { _card_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessTransferGoldRequestBean")]
  public partial class ProcessTransferGoldRequestBean : global::ProtoBuf.IExtensible
  {
    public ProcessTransferGoldRequestBean() {}
    
    private string _user_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private string _otp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"otp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string otp
    {
      get { return _otp; }
      set { _otp = value; }
    }
    private string _note = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"note", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string note
    {
      get { return _note; }
      set { _note = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessTransferResponseBean")]
  public partial class ProcessTransferResponseBean : global::ProtoBuf.IExtensible
  {
    public ProcessTransferResponseBean() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecieveGoldBean")]
  public partial class RecieveGoldBean : global::ProtoBuf.IExtensible
  {
    public RecieveGoldBean() {}
    
    private string _user_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryPaymentResponseBean")]
  public partial class HistoryPaymentResponseBean : global::ProtoBuf.IExtensible
  {
    public HistoryPaymentResponseBean() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.HistoryPaymentInfoBean> _listPayment = new global::System.Collections.Generic.List<com.nope.fishing.HistoryPaymentInfoBean>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listPayment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.HistoryPaymentInfoBean> listPayment
    {
      get { return _listPayment; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryPaymentInfoBean")]
  public partial class HistoryPaymentInfoBean : global::ProtoBuf.IExtensible
  {
    public HistoryPaymentInfoBean() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private string _note;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"note", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string note
    {
      get { return _note; }
      set { _note = value; }
    }
    private long _timeProcess = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timeProcess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timeProcess
    {
      get { return _timeProcess; }
      set { _timeProcess = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _beforeValue = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"beforeValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int beforeValue
    {
      get { return _beforeValue; }
      set { _beforeValue = value; }
    }
    private int _afterValue = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"afterValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int afterValue
    {
      get { return _afterValue; }
      set { _afterValue = value; }
    }
    private string _cardType = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cardType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cardType
    {
      get { return _cardType; }
      set { _cardType = value; }
    }
    private int _cardValue = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cardValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardValue
    {
      get { return _cardValue; }
      set { _cardValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}