//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ThirteenKiller.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKGameInfo")]
  public partial class TKGameInfo : global::ProtoBuf.IExtensible
  {
    public TKGameInfo() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TKRoomInfo> _rooms = new global::System.Collections.Generic.List<com.nope.fishing.TKRoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TKRoomInfo> rooms
    {
      get { return _rooms; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _iDOfDeletedRooms = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"iDOfDeletedRooms", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> iDOfDeletedRooms
    {
      get { return _iDOfDeletedRooms; }
    }
  
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _avatar = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKRoomInfo")]
  public partial class TKRoomInfo : global::ProtoBuf.IExtensible
  {
    public TKRoomInfo() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TKUserInfo> _users = new global::System.Collections.Generic.List<com.nope.fishing.TKUserInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TKUserInfo> users
    {
      get { return _users; }
    }
  
    private long _betLevel = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"betLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betLevel
    {
      get { return _betLevel; }
      set { _betLevel = value; }
    }
    private string _tableOwner = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tableOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableOwner
    {
      get { return _tableOwner; }
      set { _tableOwner = value; }
    }
    private int _maxPlayersOfRoom = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxPlayersOfRoom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayersOfRoom
    {
      get { return _maxPlayersOfRoom; }
      set { _maxPlayersOfRoom = value; }
    }
    private int _playersJoinedRoom = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playersJoinedRoom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playersJoinedRoom
    {
      get { return _playersJoinedRoom; }
      set { _playersJoinedRoom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKUserInfo")]
  public partial class TKUserInfo : global::ProtoBuf.IExtensible
  {
    public TKUserInfo() {}
    
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _posUser = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posUser", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posUser
    {
      get { return _posUser; }
      set { _posUser = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private bool _isMasterClient = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isMasterClient", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isMasterClient
    {
      get { return _isMasterClient; }
      set { _isMasterClient = value; }
    }
    private long _winGold = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"winGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long winGold
    {
      get { return _winGold; }
      set { _winGold = value; }
    }
    private bool _isLostFour = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isLostFour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isLostFour
    {
      get { return _isLostFour; }
      set { _isLostFour = value; }
    }
    private int _idAvatar = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"idAvatar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int idAvatar
    {
      get { return _idAvatar; }
      set { _idAvatar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKNewRoom")]
  public partial class TKNewRoom : global::ProtoBuf.IExtensible
  {
    public TKNewRoom() {}
    
    private string _tableOwner = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableOwner
    {
      get { return _tableOwner; }
      set { _tableOwner = value; }
    }
    private long _betLevel = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"betLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betLevel
    {
      get { return _betLevel; }
      set { _betLevel = value; }
    }
    private int _numberPlayers = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"numberPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numberPlayers
    {
      get { return _numberPlayers; }
      set { _numberPlayers = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKCountdown")]
  public partial class TKCountdown : global::ProtoBuf.IExtensible
  {
    public TKCountdown() {}
    
    private bool _isStartCountdown = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isStartCountdown", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isStartCountdown
    {
      get { return _isStartCountdown; }
      set { _isStartCountdown = value; }
    }
    private float _time = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKCards")]
  public partial class TKCards : global::ProtoBuf.IExtensible
  {
    public TKCards() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TKCardInfo> _listCard = new global::System.Collections.Generic.List<com.nope.fishing.TKCardInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"listCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TKCardInfo> listCard
    {
      get { return _listCard; }
    }
  
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cardListOfFines = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"cardListOfFines", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardListOfFines
    {
      get { return _cardListOfFines; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKCardInfo")]
  public partial class TKCardInfo : global::ProtoBuf.IExtensible
  {
    public TKCardInfo() {}
    
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private com.nope.fishing.TKVector2 _anchoredPosition = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"anchoredPosition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.TKVector2 anchoredPosition
    {
      get { return _anchoredPosition; }
      set { _anchoredPosition = value; }
    }
    private com.nope.fishing.TKVector2 _anchorMin = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"anchorMin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.TKVector2 anchorMin
    {
      get { return _anchorMin; }
      set { _anchorMin = value; }
    }
    private com.nope.fishing.TKVector2 _anchorMax = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"anchorMax", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.TKVector2 anchorMax
    {
      get { return _anchorMax; }
      set { _anchorMax = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKVector2")]
  public partial class TKVector2 : global::ProtoBuf.IExtensible
  {
    public TKVector2() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKUserGoFirst")]
  public partial class TKUserGoFirst : global::ProtoBuf.IExtensible
  {
    public TKUserGoFirst() {}
    
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private bool _isNewGame = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isNewGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isNewGame
    {
      get { return _isNewGame; }
      set { _isNewGame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKUserPass")]
  public partial class TKUserPass : global::ProtoBuf.IExtensible
  {
    public TKUserPass() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private bool _isPass = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isPass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPass
    {
      get { return _isPass; }
      set { _isPass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TKUserPenalty")]
  public partial class TKUserPenalty : global::ProtoBuf.IExtensible
  {
    public TKUserPenalty() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private bool _isLoser = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isLoser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isLoser
    {
      get { return _isLoser; }
      set { _isLoser = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}