//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ThreeCard.proto
namespace com.nope.fishing
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCGameInfo")]
  public partial class TCGameInfo : global::ProtoBuf.IExtensible
  {
    public TCGameInfo() {}
    
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TCRoomInfo> _rooms = new global::System.Collections.Generic.List<com.nope.fishing.TCRoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TCRoomInfo> rooms
    {
      get { return _rooms; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _iDOfDeletedRooms = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"iDOfDeletedRooms", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> iDOfDeletedRooms
    {
      get { return _iDOfDeletedRooms; }
    }
  
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _avatar = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCRoomInfo")]
  public partial class TCRoomInfo : global::ProtoBuf.IExtensible
  {
    public TCRoomInfo() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TCUserInfo> _users = new global::System.Collections.Generic.List<com.nope.fishing.TCUserInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TCUserInfo> users
    {
      get { return _users; }
    }
  
    private long _betLevel = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"betLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betLevel
    {
      get { return _betLevel; }
      set { _betLevel = value; }
    }
    private string _tableOwner = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tableOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableOwner
    {
      get { return _tableOwner; }
      set { _tableOwner = value; }
    }
    private int _maxPlayersOfRoom = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxPlayersOfRoom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayersOfRoom
    {
      get { return _maxPlayersOfRoom; }
      set { _maxPlayersOfRoom = value; }
    }
    private int _playersJoinedRoom = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playersJoinedRoom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playersJoinedRoom
    {
      get { return _playersJoinedRoom; }
      set { _playersJoinedRoom = value; }
    }
    private int _masterID = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"masterID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int masterID
    {
      get { return _masterID; }
      set { _masterID = value; }
    }
    private bool _isRoomActive = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isRoomActive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isRoomActive
    {
      get { return _isRoomActive; }
      set { _isRoomActive = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCUserInfo")]
  public partial class TCUserInfo : global::ProtoBuf.IExtensible
  {
    public TCUserInfo() {}
    
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _posUser = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posUser", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posUser
    {
      get { return _posUser; }
      set { _posUser = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private bool _isMasterClient = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isMasterClient", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isMasterClient
    {
      get { return _isMasterClient; }
      set { _isMasterClient = value; }
    }
    private long _winGold = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"winGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long winGold
    {
      get { return _winGold; }
      set { _winGold = value; }
    }
    private bool _isLostFour = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isLostFour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isLostFour
    {
      get { return _isLostFour; }
      set { _isLostFour = value; }
    }
    private int _idAvatar = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"idAvatar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int idAvatar
    {
      get { return _idAvatar; }
      set { _idAvatar = value; }
    }
    private int _roomID = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private long _betAmount = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"betAmount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betAmount
    {
      get { return _betAmount; }
      set { _betAmount = value; }
    }
    private int _scoreCard = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"scoreCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scoreCard
    {
      get { return _scoreCard; }
      set { _scoreCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCNewRoom")]
  public partial class TCNewRoom : global::ProtoBuf.IExtensible
  {
    public TCNewRoom() {}
    
    private string _tableOwner = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableOwner
    {
      get { return _tableOwner; }
      set { _tableOwner = value; }
    }
    private long _betLevel = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"betLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betLevel
    {
      get { return _betLevel; }
      set { _betLevel = value; }
    }
    private int _numberPlayers = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"numberPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numberPlayers
    {
      get { return _numberPlayers; }
      set { _numberPlayers = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCCountdown")]
  public partial class TCCountdown : global::ProtoBuf.IExtensible
  {
    public TCCountdown() {}
    
    private bool _isStartCountdown = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isStartCountdown", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isStartCountdown
    {
      get { return _isStartCountdown; }
      set { _isStartCountdown = value; }
    }
    private float _time = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCCards")]
  public partial class TCCards : global::ProtoBuf.IExtensible
  {
    public TCCards() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private int _idCard = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"idCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int idCard
    {
      get { return _idCard; }
      set { _idCard = value; }
    }
    private int _ordinalCard = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ordinalCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ordinalCard
    {
      get { return _ordinalCard; }
      set { _ordinalCard = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _listCard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"listCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> listCard
    {
      get { return _listCard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCCardInfo")]
  public partial class TCCardInfo : global::ProtoBuf.IExtensible
  {
    public TCCardInfo() {}
    
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private com.nope.fishing.TCVector2 _anchoredPosition = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"anchoredPosition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.TCVector2 anchoredPosition
    {
      get { return _anchoredPosition; }
      set { _anchoredPosition = value; }
    }
    private com.nope.fishing.TCVector2 _anchorMin = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"anchorMin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.TCVector2 anchorMin
    {
      get { return _anchorMin; }
      set { _anchorMin = value; }
    }
    private com.nope.fishing.TCVector2 _anchorMax = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"anchorMax", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.TCVector2 anchorMax
    {
      get { return _anchorMax; }
      set { _anchorMax = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCVector2")]
  public partial class TCVector2 : global::ProtoBuf.IExtensible
  {
    public TCVector2() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCUserGoFirst")]
  public partial class TCUserGoFirst : global::ProtoBuf.IExtensible
  {
    public TCUserGoFirst() {}
    
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private bool _isNewGame = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isNewGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isNewGame
    {
      get { return _isNewGame; }
      set { _isNewGame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCUserPass")]
  public partial class TCUserPass : global::ProtoBuf.IExtensible
  {
    public TCUserPass() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private bool _isPass = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isPass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPass
    {
      get { return _isPass; }
      set { _isPass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCUserPenalty")]
  public partial class TCUserPenalty : global::ProtoBuf.IExtensible
  {
    public TCUserPenalty() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private bool _isLoser = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isLoser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isLoser
    {
      get { return _isLoser; }
      set { _isLoser = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCUserBetInfo")]
  public partial class TCUserBetInfo : global::ProtoBuf.IExtensible
  {
    public TCUserBetInfo() {}
    
    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private com.nope.fishing.TCUserInfo _master = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"master", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.nope.fishing.TCUserInfo master
    {
      get { return _master; }
      set { _master = value; }
    }
    private readonly global::System.Collections.Generic.List<com.nope.fishing.TCUserInfo> _users = new global::System.Collections.Generic.List<com.nope.fishing.TCUserInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.nope.fishing.TCUserInfo> users
    {
      get { return _users; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}