// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JackpotGame.proto

package message;

public final class JackpotGameProto {
  private JackpotGameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JoinRoomRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 roomId = 1;
    /**
     * <code>optional int32 roomId = 1;</code>
     */
    boolean hasRoomId();
    /**
     * <code>optional int32 roomId = 1;</code>
     */
    int getRoomId();
  }
  /**
   * Protobuf type {@code com.nope.fishing.JoinRoomRequest}
   */
  public static final class JoinRoomRequest extends
      com.google.protobuf.GeneratedMessage
      implements JoinRoomRequestOrBuilder {
    // Use JoinRoomRequest.newBuilder() to construct.
    private JoinRoomRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinRoomRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinRoomRequest defaultInstance;
    public static JoinRoomRequest getDefaultInstance() {
      return defaultInstance;
    }

    public JoinRoomRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinRoomRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roomId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.JackpotGameProto.internal_static_com_nope_fishing_JoinRoomRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.JackpotGameProto.internal_static_com_nope_fishing_JoinRoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.JackpotGameProto.JoinRoomRequest.class, message.JackpotGameProto.JoinRoomRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinRoomRequest> PARSER =
        new com.google.protobuf.AbstractParser<JoinRoomRequest>() {
      public JoinRoomRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinRoomRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinRoomRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 roomId = 1;
    public static final int ROOMID_FIELD_NUMBER = 1;
    private int roomId_;
    /**
     * <code>optional int32 roomId = 1;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 roomId = 1;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    private void initFields() {
      roomId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, roomId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static message.JackpotGameProto.JoinRoomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static message.JackpotGameProto.JoinRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(message.JackpotGameProto.JoinRoomRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nope.fishing.JoinRoomRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements message.JackpotGameProto.JoinRoomRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_JoinRoomRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_JoinRoomRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.JackpotGameProto.JoinRoomRequest.class, message.JackpotGameProto.JoinRoomRequest.Builder.class);
      }

      // Construct using message.JackpotGameProto.JoinRoomRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_JoinRoomRequest_descriptor;
      }

      public message.JackpotGameProto.JoinRoomRequest getDefaultInstanceForType() {
        return message.JackpotGameProto.JoinRoomRequest.getDefaultInstance();
      }

      public message.JackpotGameProto.JoinRoomRequest build() {
        message.JackpotGameProto.JoinRoomRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.JackpotGameProto.JoinRoomRequest buildPartial() {
        message.JackpotGameProto.JoinRoomRequest result = new message.JackpotGameProto.JoinRoomRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomId_ = roomId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.JackpotGameProto.JoinRoomRequest) {
          return mergeFrom((message.JackpotGameProto.JoinRoomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.JackpotGameProto.JoinRoomRequest other) {
        if (other == message.JackpotGameProto.JoinRoomRequest.getDefaultInstance()) return this;
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.JackpotGameProto.JoinRoomRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.JackpotGameProto.JoinRoomRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 roomId = 1;
      private int roomId_ ;
      /**
       * <code>optional int32 roomId = 1;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 roomId = 1;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>optional int32 roomId = 1;</code>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000001;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roomId = 1;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.nope.fishing.JoinRoomRequest)
    }

    static {
      defaultInstance = new JoinRoomRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nope.fishing.JoinRoomRequest)
  }

  public interface RoomStakeInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 stepMoney = 2;
    /**
     * <code>optional int64 stepMoney = 2;</code>
     */
    boolean hasStepMoney();
    /**
     * <code>optional int64 stepMoney = 2;</code>
     */
    long getStepMoney();

    // optional int64 defaultStep = 3;
    /**
     * <code>optional int64 defaultStep = 3;</code>
     */
    boolean hasDefaultStep();
    /**
     * <code>optional int64 defaultStep = 3;</code>
     */
    long getDefaultStep();

    // optional int64 maxStep = 4;
    /**
     * <code>optional int64 maxStep = 4;</code>
     */
    boolean hasMaxStep();
    /**
     * <code>optional int64 maxStep = 4;</code>
     */
    long getMaxStep();

    // optional int64 minStep = 5;
    /**
     * <code>optional int64 minStep = 5;</code>
     */
    boolean hasMinStep();
    /**
     * <code>optional int64 minStep = 5;</code>
     */
    long getMinStep();
  }
  /**
   * Protobuf type {@code com.nope.fishing.RoomStakeInfo}
   */
  public static final class RoomStakeInfo extends
      com.google.protobuf.GeneratedMessage
      implements RoomStakeInfoOrBuilder {
    // Use RoomStakeInfo.newBuilder() to construct.
    private RoomStakeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoomStakeInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoomStakeInfo defaultInstance;
    public static RoomStakeInfo getDefaultInstance() {
      return defaultInstance;
    }

    public RoomStakeInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoomStakeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              stepMoney_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              defaultStep_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              maxStep_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              minStep_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.JackpotGameProto.internal_static_com_nope_fishing_RoomStakeInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.JackpotGameProto.internal_static_com_nope_fishing_RoomStakeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.JackpotGameProto.RoomStakeInfo.class, message.JackpotGameProto.RoomStakeInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<RoomStakeInfo> PARSER =
        new com.google.protobuf.AbstractParser<RoomStakeInfo>() {
      public RoomStakeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomStakeInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoomStakeInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 stepMoney = 2;
    public static final int STEPMONEY_FIELD_NUMBER = 2;
    private long stepMoney_;
    /**
     * <code>optional int64 stepMoney = 2;</code>
     */
    public boolean hasStepMoney() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 stepMoney = 2;</code>
     */
    public long getStepMoney() {
      return stepMoney_;
    }

    // optional int64 defaultStep = 3;
    public static final int DEFAULTSTEP_FIELD_NUMBER = 3;
    private long defaultStep_;
    /**
     * <code>optional int64 defaultStep = 3;</code>
     */
    public boolean hasDefaultStep() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 defaultStep = 3;</code>
     */
    public long getDefaultStep() {
      return defaultStep_;
    }

    // optional int64 maxStep = 4;
    public static final int MAXSTEP_FIELD_NUMBER = 4;
    private long maxStep_;
    /**
     * <code>optional int64 maxStep = 4;</code>
     */
    public boolean hasMaxStep() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 maxStep = 4;</code>
     */
    public long getMaxStep() {
      return maxStep_;
    }

    // optional int64 minStep = 5;
    public static final int MINSTEP_FIELD_NUMBER = 5;
    private long minStep_;
    /**
     * <code>optional int64 minStep = 5;</code>
     */
    public boolean hasMinStep() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 minStep = 5;</code>
     */
    public long getMinStep() {
      return minStep_;
    }

    private void initFields() {
      stepMoney_ = 0L;
      defaultStep_ = 0L;
      maxStep_ = 0L;
      minStep_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, stepMoney_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, defaultStep_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, maxStep_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, minStep_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, stepMoney_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, defaultStep_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, maxStep_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, minStep_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static message.JackpotGameProto.RoomStakeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static message.JackpotGameProto.RoomStakeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(message.JackpotGameProto.RoomStakeInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nope.fishing.RoomStakeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements message.JackpotGameProto.RoomStakeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_RoomStakeInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_RoomStakeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.JackpotGameProto.RoomStakeInfo.class, message.JackpotGameProto.RoomStakeInfo.Builder.class);
      }

      // Construct using message.JackpotGameProto.RoomStakeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stepMoney_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        defaultStep_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxStep_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        minStep_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_RoomStakeInfo_descriptor;
      }

      public message.JackpotGameProto.RoomStakeInfo getDefaultInstanceForType() {
        return message.JackpotGameProto.RoomStakeInfo.getDefaultInstance();
      }

      public message.JackpotGameProto.RoomStakeInfo build() {
        message.JackpotGameProto.RoomStakeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.JackpotGameProto.RoomStakeInfo buildPartial() {
        message.JackpotGameProto.RoomStakeInfo result = new message.JackpotGameProto.RoomStakeInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stepMoney_ = stepMoney_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.defaultStep_ = defaultStep_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxStep_ = maxStep_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.minStep_ = minStep_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.JackpotGameProto.RoomStakeInfo) {
          return mergeFrom((message.JackpotGameProto.RoomStakeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.JackpotGameProto.RoomStakeInfo other) {
        if (other == message.JackpotGameProto.RoomStakeInfo.getDefaultInstance()) return this;
        if (other.hasStepMoney()) {
          setStepMoney(other.getStepMoney());
        }
        if (other.hasDefaultStep()) {
          setDefaultStep(other.getDefaultStep());
        }
        if (other.hasMaxStep()) {
          setMaxStep(other.getMaxStep());
        }
        if (other.hasMinStep()) {
          setMinStep(other.getMinStep());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.JackpotGameProto.RoomStakeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.JackpotGameProto.RoomStakeInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 stepMoney = 2;
      private long stepMoney_ ;
      /**
       * <code>optional int64 stepMoney = 2;</code>
       */
      public boolean hasStepMoney() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 stepMoney = 2;</code>
       */
      public long getStepMoney() {
        return stepMoney_;
      }
      /**
       * <code>optional int64 stepMoney = 2;</code>
       */
      public Builder setStepMoney(long value) {
        bitField0_ |= 0x00000001;
        stepMoney_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 stepMoney = 2;</code>
       */
      public Builder clearStepMoney() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stepMoney_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 defaultStep = 3;
      private long defaultStep_ ;
      /**
       * <code>optional int64 defaultStep = 3;</code>
       */
      public boolean hasDefaultStep() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 defaultStep = 3;</code>
       */
      public long getDefaultStep() {
        return defaultStep_;
      }
      /**
       * <code>optional int64 defaultStep = 3;</code>
       */
      public Builder setDefaultStep(long value) {
        bitField0_ |= 0x00000002;
        defaultStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 defaultStep = 3;</code>
       */
      public Builder clearDefaultStep() {
        bitField0_ = (bitField0_ & ~0x00000002);
        defaultStep_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 maxStep = 4;
      private long maxStep_ ;
      /**
       * <code>optional int64 maxStep = 4;</code>
       */
      public boolean hasMaxStep() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 maxStep = 4;</code>
       */
      public long getMaxStep() {
        return maxStep_;
      }
      /**
       * <code>optional int64 maxStep = 4;</code>
       */
      public Builder setMaxStep(long value) {
        bitField0_ |= 0x00000004;
        maxStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 maxStep = 4;</code>
       */
      public Builder clearMaxStep() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxStep_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 minStep = 5;
      private long minStep_ ;
      /**
       * <code>optional int64 minStep = 5;</code>
       */
      public boolean hasMinStep() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 minStep = 5;</code>
       */
      public long getMinStep() {
        return minStep_;
      }
      /**
       * <code>optional int64 minStep = 5;</code>
       */
      public Builder setMinStep(long value) {
        bitField0_ |= 0x00000008;
        minStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 minStep = 5;</code>
       */
      public Builder clearMinStep() {
        bitField0_ = (bitField0_ & ~0x00000008);
        minStep_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.nope.fishing.RoomStakeInfo)
    }

    static {
      defaultInstance = new RoomStakeInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nope.fishing.RoomStakeInfo)
  }

  public interface RoomPotResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 roomId = 2;
    /**
     * <code>optional int32 roomId = 2;</code>
     */
    boolean hasRoomId();
    /**
     * <code>optional int32 roomId = 2;</code>
     */
    int getRoomId();

    // optional int64 pot = 3;
    /**
     * <code>optional int64 pot = 3;</code>
     */
    boolean hasPot();
    /**
     * <code>optional int64 pot = 3;</code>
     */
    long getPot();
  }
  /**
   * Protobuf type {@code com.nope.fishing.RoomPotResponse}
   */
  public static final class RoomPotResponse extends
      com.google.protobuf.GeneratedMessage
      implements RoomPotResponseOrBuilder {
    // Use RoomPotResponse.newBuilder() to construct.
    private RoomPotResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoomPotResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoomPotResponse defaultInstance;
    public static RoomPotResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RoomPotResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoomPotResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              roomId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              pot_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.JackpotGameProto.internal_static_com_nope_fishing_RoomPotResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.JackpotGameProto.internal_static_com_nope_fishing_RoomPotResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.JackpotGameProto.RoomPotResponse.class, message.JackpotGameProto.RoomPotResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RoomPotResponse> PARSER =
        new com.google.protobuf.AbstractParser<RoomPotResponse>() {
      public RoomPotResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomPotResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoomPotResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 roomId = 2;
    public static final int ROOMID_FIELD_NUMBER = 2;
    private int roomId_;
    /**
     * <code>optional int32 roomId = 2;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 roomId = 2;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    // optional int64 pot = 3;
    public static final int POT_FIELD_NUMBER = 3;
    private long pot_;
    /**
     * <code>optional int64 pot = 3;</code>
     */
    public boolean hasPot() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 pot = 3;</code>
     */
    public long getPot() {
      return pot_;
    }

    private void initFields() {
      roomId_ = 0;
      pot_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, roomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, pot_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, pot_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static message.JackpotGameProto.RoomPotResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.JackpotGameProto.RoomPotResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomPotResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.JackpotGameProto.RoomPotResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomPotResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static message.JackpotGameProto.RoomPotResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomPotResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static message.JackpotGameProto.RoomPotResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static message.JackpotGameProto.RoomPotResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static message.JackpotGameProto.RoomPotResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(message.JackpotGameProto.RoomPotResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nope.fishing.RoomPotResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements message.JackpotGameProto.RoomPotResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_RoomPotResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_RoomPotResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.JackpotGameProto.RoomPotResponse.class, message.JackpotGameProto.RoomPotResponse.Builder.class);
      }

      // Construct using message.JackpotGameProto.RoomPotResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pot_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.JackpotGameProto.internal_static_com_nope_fishing_RoomPotResponse_descriptor;
      }

      public message.JackpotGameProto.RoomPotResponse getDefaultInstanceForType() {
        return message.JackpotGameProto.RoomPotResponse.getDefaultInstance();
      }

      public message.JackpotGameProto.RoomPotResponse build() {
        message.JackpotGameProto.RoomPotResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.JackpotGameProto.RoomPotResponse buildPartial() {
        message.JackpotGameProto.RoomPotResponse result = new message.JackpotGameProto.RoomPotResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomId_ = roomId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pot_ = pot_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.JackpotGameProto.RoomPotResponse) {
          return mergeFrom((message.JackpotGameProto.RoomPotResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.JackpotGameProto.RoomPotResponse other) {
        if (other == message.JackpotGameProto.RoomPotResponse.getDefaultInstance()) return this;
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasPot()) {
          setPot(other.getPot());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.JackpotGameProto.RoomPotResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.JackpotGameProto.RoomPotResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 roomId = 2;
      private int roomId_ ;
      /**
       * <code>optional int32 roomId = 2;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 roomId = 2;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>optional int32 roomId = 2;</code>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000001;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roomId = 2;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0;
        onChanged();
        return this;
      }

      // optional int64 pot = 3;
      private long pot_ ;
      /**
       * <code>optional int64 pot = 3;</code>
       */
      public boolean hasPot() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 pot = 3;</code>
       */
      public long getPot() {
        return pot_;
      }
      /**
       * <code>optional int64 pot = 3;</code>
       */
      public Builder setPot(long value) {
        bitField0_ |= 0x00000002;
        pot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 pot = 3;</code>
       */
      public Builder clearPot() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pot_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.nope.fishing.RoomPotResponse)
    }

    static {
      defaultInstance = new RoomPotResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nope.fishing.RoomPotResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nope_fishing_JoinRoomRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nope_fishing_JoinRoomRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nope_fishing_RoomStakeInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nope_fishing_RoomStakeInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nope_fishing_RoomPotResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nope_fishing_RoomPotResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021JackpotGame.proto\022\020com.nope.fishing\"!\n" +
      "\017JoinRoomRequest\022\016\n\006roomId\030\001 \001(\005\"Y\n\rRoom" +
      "StakeInfo\022\021\n\tstepMoney\030\002 \001(\003\022\023\n\013defaultS" +
      "tep\030\003 \001(\003\022\017\n\007maxStep\030\004 \001(\003\022\017\n\007minStep\030\005 " +
      "\001(\003\".\n\017RoomPotResponse\022\016\n\006roomId\030\002 \001(\005\022\013" +
      "\n\003pot\030\003 \001(\003B\035\n\007messageB\020JackpotGameProto" +
      "H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_nope_fishing_JoinRoomRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_nope_fishing_JoinRoomRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nope_fishing_JoinRoomRequest_descriptor,
              new java.lang.String[] { "RoomId", });
          internal_static_com_nope_fishing_RoomStakeInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_nope_fishing_RoomStakeInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nope_fishing_RoomStakeInfo_descriptor,
              new java.lang.String[] { "StepMoney", "DefaultStep", "MaxStep", "MinStep", });
          internal_static_com_nope_fishing_RoomPotResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_nope_fishing_RoomPotResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nope_fishing_RoomPotResponse_descriptor,
              new java.lang.String[] { "RoomId", "Pot", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
